global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:9101']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
