apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: postgres:15
            envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            command:
            - sh
            - -c
            - pg_dump -h postgres -U $POSTGRES_USER $POSTGRES_DB > /backup/backup.sql
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: data-postgres-0
