apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.processor.replicas }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: {{ .Values.processor.image }}
        ports:
        - containerPort: {{ .Values.processor.port }}
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        volumeMounts:
        - name: models
          mountPath: /data/models
        - name: faiss
          mountPath: /data/faiss
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
      - name: faiss
        persistentVolumeClaim:
          claimName: faiss-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: processor
  ports:
  - port: {{ .Values.processor.port }}
    targetPort: {{ .Values.processor.port }}
